#! /bin/bash
# Script to start bird, then never return (as bird runs daemonised).
# Single argument is config file; must be in /etc/bird/
/usr/sbin/bird -s /var/run/bird.ctl -c /etc/bird/$1 && sleep infinity
